apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ml-project
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30005 
